[book]
authors = ["Narayan G. Maharjan"]
language = "en"
src = "src"
title = "Cardano Projects - Metrics & Insights"


[build]
build-dir = "docs" 


[output.html]
default-theme = "light"
smart-punctuation = true
mathjax-support = false
copy-fonts = true
git-repository-url = "https://github.com/Workharu/cardano-projects-docs"
cname = "docs.cardanoprojects.com"

[output.html.playground]
editable = false 